### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by LindaEng** [l1nd53y/Brilliant-Bananas-Project#20]
Ahoy Brilliant Bananas,

Just dropping by to let you know that your task-board looks AMAZING! Brilliant industry-standard norms (adding title, checkboxes, specificity of which end). Your task-board is your North Star, and your crew know exactly where they are going. I can tell without even checking into your breakout room that your team has excellent communication just by looking at your project board. I also appreciate the tiers column!

I'd like to add some constructive feedback:

-Please convert the tickets into issues before moving them around the project board. When you add labels to your issues, your team can identify whether one card takes precedence over another. Also, when your team conduct daily stand-ups, your team might agree that a major bug needs to supersede any feature. It would be a lot easier to re-organize and re-prioritize if each issue had clear labels.

- By converting the cards into issues, it would also be easier to allocate the work across your team. Everyone knows who's responsible for what. This makes communication a lot more seamless! If a team-member is working on a similar card, you can refer to them if you have any questions. Hard to do so if you don't know who's assigned to what.

Other than that, your team definitely lives up to the name! 

-Linda

**Comment by ceckles** [comment]
thank you for the feedback
